### ISSUE TITLE
 A Question About Adding Artists

### ISSUE THREAD

**Issue by HelgenX** [kaikalii/stable-diffusion-artists#2]
I'd like to add an artist I like. Where is the folder to modify these type of files? Thanks.

**Comment by kaikalii** [comment]
You can make a PR.
Simply add artist info to the readme with a format similar to the others.
Put the picture for each artist in the images folder.

**Comment by HelgenX** [comment]
> You can make a PR. Simply add artist info to the readme with a format similar to the others. Put the picture for each artist in the images folder.

So I did manage to find the artist folder, and copied the image format, but where is this readme file that I use for the artist info? Which folder? Thanks a lot!

**Comment by kaikalii** [comment]
It's not in a folder. It's at the top level of the repo structure. It's `readme.md`.

**Comment by HelgenX** [comment]
Thank you very nuch, I have figured it out!
